<?php
/**ORAX™ Framework is a vanilla and evolving framework for developing websites, applications, and APIs using web technology.
 * Creator: Osawere™ O. Anthony - @iamodao - www.osawere.com  © August 2020 | Apache License
 * ==== === ===== === ===== === ===== ======= ==== ========= ==== ==== ======= ======== ======== === ===
 * SWITCH ~ application switch handler • DEPENDENCY»
 */

#HARVERST APP
require(oRouter::Path('oInitFile'));
echo oDump::Neat($aHavest);
?>